function [values,car_labels] = car_montage_2(values,labels)

car_labels = labels;
brain_channels = {'Fp1',...
    'F7',...
    'T3',...
    'T5',...
    'O1',...
    'Fp2',...
    'F8',...
    'T4',...
    'T6',...
    'O2',...
    'F3',...
    'C3',...
    'P3',...
    'F4',...
    'C4',...
    'P4',...
    'Fz',...
    'Cz'};

% Take average of the brain channels
is_brain = ismember(labels,brain_channels);
avg = nanmean(values(:,is_brain),2);

% Do car (just average the non-skip chs)
values(:,is_brain) = values(:,is_brain) - repmat(avg,1,sum(is_brain));

for i = 1:length(labels)
    if is_brain(i) == 1
        car_labels{i} = [labels{i},'-CAR'];
    end
end

end